/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SoalPertemuan5;
import SoalPertemuan5.Dao.DetailPemesananDAO;
import SoalPertemuan5.Dao.MenuDAO;
import SoalPertemuan5.Dao.PemesananDAO;

import SoalPertemuan5.Model.Menu;
/**
 *
 * @author DELL
 */

public class MenuFrame extends javax.swing.JInternalFrame {
    MenuDAO dao = new MenuDAO();
    /**
     * Creates new form Menu
     */
    public MenuFrame() {
        initComponents();
        loadMenu();
        
        
        // Paket 1
        JPaket1.addActionListener(e -> {
            String pilih = JPaket1.getSelectedItem().toString();
            int harga = dao.getHargaByNama(pilih);
            hrgPaket1.setText(String.valueOf(harga));
        });

        // Paket 2
        JPaket2.addActionListener(e -> {
           String pilih = JPaket2.getSelectedItem().toString();
           int harga = dao.getHargaByNama(pilih);
           hrgPaket2.setText(String.valueOf(harga));
       });

       JPaket3.addActionListener(e -> {
           String pilih = JPaket3.getSelectedItem().toString();
           int harga = dao.getHargaByNama(pilih);
           hrgPaket3.setText(String.valueOf(harga));
       });
        
        hrgPaket1.setEditable(false);
        hrgPaket2.setEditable(false);
        hrgPaket3.setEditable(false);

        byrPaket1.setEditable(false);
        byrPaket2.setEditable(false);
        byrPaket3.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputMeja = new javax.swing.JTextField();
        btnOke = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JPaket1 = new javax.swing.JComboBox<>();
        JPaket2 = new javax.swing.JComboBox<>();
        JPaket3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hrgPaket1 = new javax.swing.JTextField();
        hrgPaket2 = new javax.swing.JTextField();
        hrgPaket3 = new javax.swing.JTextField();
        qtyPaket1 = new javax.swing.JTextField();
        qtyPaket2 = new javax.swing.JTextField();
        qtyPaket3 = new javax.swing.JTextField();
        byrPaket1 = new javax.swing.JTextField();
        byrPaket2 = new javax.swing.JTextField();
        byrPaket3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputTotalPesanan = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        inputNamaPelanggan = new javax.swing.JTextField();

        jLabel1.setText("PESANAN");

        jLabel2.setText("NO.MEJA");

        inputMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMejaActionPerformed(evt);
            }
        });

        btnOke.setText("OK");
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });

        jLabel3.setText("HARGA");

        JPaket1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nasi Putih", "Nasi Goreng", "Nasi Capcay" }));
        JPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPaket1ActionPerformed(evt);
            }
        });

        JPaket2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ayam  Penyet", "Ayam Bakar", "Ayam Goreng" }));
        JPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPaket2ActionPerformed(evt);
            }
        });

        JPaket3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aqua", "Jus Alpukat", "Jus Jeruk" }));

        jLabel4.setText("JUML.BELI");

        jLabel5.setText("BAYAR");

        jLabel6.setText("TOTAL PESANAN");

        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Pelanggan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel5)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hrgPaket1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(hrgPaket2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hrgPaket3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(qtyPaket1)
                                                .addComponent(qtyPaket2)
                                                .addComponent(qtyPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(byrPaket1)
                                            .addComponent(byrPaket2)
                                            .addComponent(byrPaket3)
                                            .addComponent(inputTotalPesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnOke))))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPaket1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPaket2, 0, 1, Short.MAX_VALUE)
                    .addComponent(JPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byrPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byrPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrgPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byrPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputTotalPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBayar)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        int h1 = hrgPaket1.getText().isEmpty() ? 0 : Integer.parseInt(hrgPaket1.getText());
        int h2 = hrgPaket2.getText().isEmpty() ? 0 : Integer.parseInt(hrgPaket2.getText());
        int h3 = hrgPaket3.getText().isEmpty() ? 0 : Integer.parseInt(hrgPaket3.getText());
    
        // qty
        int q1 = qtyPaket1.getText().isEmpty() ? 0 : Integer.parseInt(qtyPaket1.getText());
        int q2 = qtyPaket2.getText().isEmpty() ? 0 :Integer.parseInt(qtyPaket2.getText());
        int q3 = qtyPaket3.getText().isEmpty() ? 0 :Integer.parseInt(qtyPaket3.getText());
        
        // total
        int total1 = h1*q1;
        int total2 = h2*q2;
        int total3 = h3*q3;
        
        //bayar
        byrPaket1.setText(String.valueOf(total1));
        byrPaket2.setText(String.valueOf(total2));
        byrPaket3.setText(String.valueOf(total3));
        
        int totalSemua = total1 + total2 + total3;
        inputTotalPesanan.setText(String.valueOf(totalSemua));
    }//GEN-LAST:event_btnOkeActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed

        if (inputNamaPelanggan.getText().isEmpty() || inputMeja.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Isi nama dan meja dulu!");
            return;
        }

        if (inputTotalPesanan.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Hitung total dulu (klik OK)!");
            return;
        }

        PemesananDAO daoPesan = new PemesananDAO();
        DetailPemesananDAO daoDetail = new DetailPemesananDAO();
        MenuDAO menuDAO = new MenuDAO();

        int idPesanan = daoPesan.simpan(
            inputNamaPelanggan.getText(),
            inputMeja.getText(),
            Integer.parseInt(inputTotalPesanan.getText())
        );

        // ================= PAKET 1 =================
        if (!qtyPaket1.getText().isEmpty() && !qtyPaket1.getText().equals("0")) {
            int idMenu1 = menuDAO.getIdByNama(JPaket1.getSelectedItem().toString());

            daoDetail.simpan(
                idPesanan,
                idMenu1,
                Integer.parseInt(qtyPaket1.getText()),
                Integer.parseInt(byrPaket1.getText())
            );
        }

        // ================= PAKET 2 =================
        if (!qtyPaket2.getText().isEmpty() && !qtyPaket2.getText().equals("0")) {
            int idMenu2 = menuDAO.getIdByNama(JPaket2.getSelectedItem().toString());

            daoDetail.simpan(
                idPesanan,
                idMenu2,
                Integer.parseInt(qtyPaket2.getText()),
                Integer.parseInt(byrPaket2.getText())
            );
        }

        // ================= PAKET 3 =================
        if (!qtyPaket3.getText().isEmpty() && !qtyPaket3.getText().equals("0")) {
            int idMenu3 = menuDAO.getIdByNama(JPaket3.getSelectedItem().toString());

            daoDetail.simpan(
                idPesanan,
                idMenu3,
                Integer.parseInt(qtyPaket3.getText()),
                Integer.parseInt(byrPaket3.getText())
            );
        }

        // ================= PINDAH KE PEMBAYARAN =================
        Pembayaran p = new Pembayaran();

        p.setDataDetail(
            inputMeja.getText(),

            JPaket1.getSelectedItem().toString(),
            hrgPaket1.getText(),
            qtyPaket1.getText(),
            byrPaket1.getText(),

            JPaket2.getSelectedItem().toString(),
            hrgPaket2.getText(),
            qtyPaket2.getText(),
            byrPaket2.getText(),

            JPaket3.getSelectedItem().toString(),
            hrgPaket3.getText(),
            qtyPaket3.getText(),
            byrPaket3.getText(),

            inputTotalPesanan.getText()
        );

        getDesktopPane().add(p);
        p.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void JPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPaket1ActionPerformed

    }//GEN-LAST:event_JPaket1ActionPerformed

    private void JPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPaket2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPaket2ActionPerformed

    private void inputMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMejaActionPerformed
    private void loadMenu() {
        JPaket1.removeAllItems();
        JPaket2.removeAllItems();
        JPaket3.removeAllItems();

        for (Menu m : dao.getMenuByKategori("paket1")) {
            JPaket1.addItem(m.getNama());
        }

        for (Menu m : dao.getMenuByKategori("paket2")) {
            JPaket2.addItem(m.getNama());
        }

        for (Menu m : dao.getMenuByKategori("paket3")) {
            JPaket3.addItem(m.getNama());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JPaket1;
    private javax.swing.JComboBox<String> JPaket2;
    private javax.swing.JComboBox<String> JPaket3;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnOke;
    private javax.swing.JTextField byrPaket1;
    private javax.swing.JTextField byrPaket2;
    private javax.swing.JTextField byrPaket3;
    private javax.swing.JTextField hrgPaket1;
    private javax.swing.JTextField hrgPaket2;
    private javax.swing.JTextField hrgPaket3;
    private javax.swing.JTextField inputMeja;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputTotalPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField qtyPaket1;
    private javax.swing.JTextField qtyPaket2;
    private javax.swing.JTextField qtyPaket3;
    // End of variables declaration//GEN-END:variables
}
