/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SoalPertemuan5;
import SoalPertemuan5.Dao.PembayaranDao;
import SoalPertemuan5.Logic.DecisionTree;
import SoalPertemuan5.MenuFrame;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Pembayaran extends javax.swing.JInternalFrame {
    int q1, q2, q3;
    public Pembayaran() {
        initComponents();
        Tabel.setRowHeight(25);
        Tabel.setShowGrid(true);
        Tabel.setGridColor(new java.awt.Color(200,200,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoMeja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPesanan = new javax.swing.JTextField();
        txtPPN = new javax.swing.JTextField();
        inputPembayaran = new javax.swing.JTextField();
        outputKembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputData = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        outputPendapatan = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembayaran"));

        jLabel1.setText("NO. MEJA");

        jLabel2.setText("TOTAL PESANAN");

        jLabel3.setText("PPN");

        jLabel4.setText("UANG PEMBAYARAN");

        jLabel5.setText("UANG KEMBALI");

        OutputData.setColumns(20);
        OutputData.setRows(5);
        jScrollPane1.setViewportView(OutputData);

        jButton1.setText("STRUK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtPPN)
                            .addComponent(inputPembayaran)
                            .addComponent(outputKembali)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTotalPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(outputKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnBayar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Meja", "Menu", "Harga", "Jumlah", "Subtotal"
            }
        ));
        Tabel.setShowHorizontalLines(true);
        Tabel.setShowVerticalLines(true);
        jScrollPane3.setViewportView(Tabel);

        jLabel6.setText("TOTAL PENDAPATAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(outputPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(outputPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed

       if (inputPembayaran.getText().isEmpty()) {
           javax.swing.JOptionPane.showMessageDialog(null, "Isi uang pembayaran dulu!");
           return;
       }

       int total = Integer.parseInt(txtTotalPesanan.getText());
       int ppn = Integer.parseInt(txtPPN.getText());
       int bayar = Integer.parseInt(inputPembayaran.getText());

       int totalAkhir = total + ppn;


       if (bayar < totalAkhir) {
           javax.swing.JOptionPane.showMessageDialog(null, "Uang tidak cukup!");
           return;
       }

       int kembali = bayar - totalAkhir;
       outputKembali.setText(String.valueOf(kembali));
       
        int totalItem = q1 + q2 + q3;
        String rekomendasi = DecisionTree.getRekomendasi(total, totalItem);
       // ================= STRUK =================
       OutputData.setText(
           "===== STRUK PEMBAYARAN =====\n" +
           "No Meja : " + txtNoMeja.getText() + "\n" +
           "Total   : " + total + "\n" +
           "PPN     : " + ppn + "\n" +
           "Bayar   : " + bayar + "\n" +
           "Kembali : " + kembali + "\n" +
           "============================"
       );
        OutputData.append("\n\n=== ANALISIS KEUANGAN ===\n" + rekomendasi);

       // ================= SIMPAN KE DATABASE =================
       PembayaranDao dao = new PembayaranDao();

       dao.simpan(
           txtNoMeja.getText(),
           total,
           ppn,
           bayar,
           kembali
       );

       // ================= TOTAL PENDAPATAN DARI DB =================
       
       int totalPendapatan = dao.getTotalPendapatan();
       outputPendapatan.setText(String.valueOf(totalPendapatan));
        try {
            OutputData.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
       javax.swing.JOptionPane.showMessageDialog(null, "Pembayaran berhasil!");
    }//GEN-LAST:event_btnBayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputData;
    private javax.swing.JTable Tabel;
    private javax.swing.JButton btnBayar;
    private javax.swing.JTextField inputPembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField outputKembali;
    private javax.swing.JTextField outputPendapatan;
    private javax.swing.JTextField txtNoMeja;
    private javax.swing.JTextField txtPPN;
    private javax.swing.JTextField txtTotalPesanan;
    // End of variables declaration//GEN-END:variables

    void setData(String meja, String total) {
       txtNoMeja.setText(meja);
       txtTotalPesanan.setText(total);
         // HITUNG PPN DI SINI
        int t = Integer.parseInt(total);
        int ppn = t * 11 / 100;

        txtPPN.setText(String.valueOf(ppn));
    }

    public void setDataDetail(
        String meja,

        String menu1, String harga1, String qty1, String sub1,
        String menu2, String harga2, String qty2, String sub2,
        String menu3, String harga3, String qty3, String sub3,

        String total
    ) {
        txtNoMeja.setText(meja);
        txtTotalPesanan.setText(total);

        int t = Integer.parseInt(total);
        int ppn = t * 11 / 100;
        txtPPN.setText(String.valueOf(ppn));

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) Tabel.getModel();

        model.setRowCount(0); // reset tabel

        // Paket 1
        if (!qty1.equals("0") && !qty1.isEmpty()) {
            model.addRow(new Object[]{meja, menu1, harga1, qty1, sub1});
        }

        // Paket 2
        if (!qty2.equals("0") && !qty2.isEmpty()) {
            model.addRow(new Object[]{meja, menu2, harga2, qty2, sub2});
        }

        // Paket 3
        if (!qty3.equals("0") && !qty3.isEmpty()) {
            model.addRow(new Object[]{meja, menu3, harga3, qty3, sub3});
        }
        this.q1 = qty1.isEmpty() ? 0 : Integer.parseInt(qty1);
        this.q2 = qty2.isEmpty() ? 0 : Integer.parseInt(qty2);
        this.q3 = qty3.isEmpty() ? 0 : Integer.parseInt(qty3);
        model.addRow(new Object[]{
            "",
            "",
            "",
            "TOTAL",
            total
        });

        model.addRow(new Object[]{
            "",
            "",
            "",
            "PPN",
            ppn
        });

        model.addRow(new Object[]{
            "",
            "",
            "",
            "TOTAL AKHIR",
            (t + ppn)
        });
    }
    
}
